{
  description = "Percy CLI binary built with pkg via Nix";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
    flake-schemas.url = "github:DeterminateSystems/flake-schemas";
    bun2nix.url = "github:nix-community/bun2nix";
    bun2nix.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, flake-schemas, bun2nix }:
    let
      systems = [
        "aarch64-linux"
        "aarch64-darwin"
        "x86_64-linux"
        "x86_64-darwin"
      ];

      forAllSystems = f: nixpkgs.lib.genAttrs systems (system:
        let
          # Apply bun2nix overlay to pkgs for easier access to bun2nix functions
          pkgs = import nixpkgs {
            inherit system;
            overlays = [ bun2nix.overlays.default ];
          };
        in
        f pkgs system);

    in {
      schemas = flake-schemas.schemas;

      packages = forAllSystems (pkgs: system:
        let
          cfg        = import ./nix/percy-config.nix { inherit pkgs; };
          srcPatched = import ./nix/src-patched.nix { inherit pkgs; version = cfg.version; };

          # Layer 2: node tree build using bun2nix
          # bun2nix provides offline, reproducible builds from bun.lock
          # See https://nix-community.github.io/bun2nix/ for documentation
          
          # Check if bun.lock exists (required for bun2nix)
          # If not, it needs to be generated first with: bun install
          hasBunLock = builtins.pathExists "${srcPatched}/bun.lock";
          
          # Import bun.nix if it exists (generated by bun2nix CLI tool)
          # The bun.nix file should be generated by running: bun2nix -o bun.nix
          bunNixPath = if builtins.pathExists "${srcPatched}/bun.nix" then
            "${srcPatched}/bun.nix"
          else if hasBunLock then
            throw ''
              bun.lock found but bun.nix not found. 
              To generate bun.nix, run: bun2nix -o bun.nix
              Or add to package.json: "postinstall": "bun2nix -o bun.nix"
            ''
          else
            throw ''
              bun.lock not found. To use bun2nix:
              1. Run 'bun install' to generate bun.lock
              2. Run 'bun2nix -o bun.nix' to generate bun.nix
              Or add to package.json: "postinstall": "bun2nix -o bun.nix"
            '';
          
          # Fetch Bun dependencies offline using bun2nix
          # This creates a Bun-compatible cache from bun.nix
          bunDeps = pkgs.bun2nix.fetchBunDeps {
            bunNix = bunNixPath;
          };
          
          # Build the complete project with bun2nix
          # Using stdenv.mkDerivation with bun2nix hook for offline installs
          nodeTree = pkgs.stdenv.mkDerivation {
            pname = "percy-cli-node-tree";
            version = cfg.version;
            src = srcPatched;
            
            nativeBuildInputs = with pkgs; [
              bun
              nodejs
              bun2nix.hook  # Provides offline install capability
            ];
            
            # bun2nix hook uses this to find the offline cache
            inherit bunDeps;
            
            # Build phase - run lerna and babel
            buildPhase = ''
              export HOME="$TMPDIR/home"
              mkdir -p "$HOME"

              # bun2nix.hook sets BUN_INSTALL_CACHE_DIR automatically
              # Install dependencies from offline cache
              echo "Installing dependencies from bun2nix cache..."
              bun install --frozen-lockfile --no-save

              # Add node_modules/.bin to PATH for build tools
              export PATH="$PWD/node_modules/.bin:$PATH"

              # Run lerna build (or bun run build if using Bun workspaces)
              bun run build || lerna run build --stream

              # Run babel build_cjs directly
              BABEL_ENV=dev babel packages -d build || true
              if [ -d build ]; then
                cp -R build/* packages/
              fi
            '';
            
            installPhase = ''
              mkdir -p $out
              cp -R . $out
            '';
          };

          # Layer 3: prepared CLI tree (patched for pkg)
          preparedCli = import ./nix/prepared-cli.nix {
            inherit pkgs;
            nodeTree = nodeTree;
            version = cfg.version;
          };

          pkgWrapper = import ./nix/pkg-wrapper.nix { inherit pkgs; };

          # Layer 4: pkg-wrapped CLI binary
          percyCli = pkgWrapper {
            pname = "percy-cli";
            version = cfg.version;
            pkgTarget = cfg.pkgTargetFor system;
            preparedCli = preparedCli;
            entrypoint = "./packages/cli/bin/run.cjs";
            binaryName = "percy";
          };

        in {
          src-patched   = srcPatched;
          node-tree     = nodeTree;
          prepared-cli  = preparedCli;
          percy-cli     = percyCli;
          default       = percyCli;
        });

      apps = forAllSystems (pkgs: system: {
        percy-cli = {
          type = "app";
          program = "${self.packages.${system}.percy-cli}/bin/percy";
          meta.description = "Percy CLI executable";
        };
      });

      devShells = forAllSystems (pkgs: system: {
        default = import ./nix/dev-shell.nix { inherit pkgs; };
      });

      checks = forAllSystems (pkgs: system:
        let
          percyCli = self.packages.${system}.percy-cli;
        in
        {
          # Build verification checks
          src_patched = self.packages.${system}.src-patched;
          node_tree = self.packages.${system}.node-tree;
          prepared_cli = self.packages.${system}.prepared-cli;
          
          # Binary existence and executability check
          binary_exists = pkgs.runCommand "percy-binary-exists-check" {} ''
            if [ ! -f ${percyCli}/bin/percy ]; then
              echo "ERROR: Binary not found at ${percyCli}/bin/percy"
              exit 1
            fi
            if [ ! -x ${percyCli}/bin/percy ]; then
              echo "ERROR: Binary is not executable"
              exit 1
            fi
            echo "✓ Binary exists and is executable"
            touch $out
          '';
          
          # Basic smoke test - check that binary runs (--version or --help)
          binary_smoke_test = pkgs.runCommand "percy-binary-smoke-test" {
            nativeBuildInputs = [ percyCli ];
          } ''
            # Try --version first, fall back to --help if that doesn't work
            if ${percyCli}/bin/percy --version >/dev/null 2>&1 || \
               ${percyCli}/bin/percy --help >/dev/null 2>&1; then
              echo "✓ Binary runs successfully"
            else
              echo "ERROR: Binary failed to run"
              exit 1
            fi
            touch $out
          '';
          
          # Default check (builds the full package)
          default = percyCli;
        }
      );
    };
}